# Generated by Django 5.2.6 on 2025-09-27 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_email_alter_company_name_and_more'),
        ('employees', '0003_remove_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'إضافة'), ('deduction', 'حسم')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='salaries.monthlypayslip')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('withdraw_allowed_percentage', models.PositiveIntegerField(help_text='النسبة المئوية من الراتب الشهري المسموح بسحبها', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_contracts', to='companies.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_contract', to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='salary_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='salaries.salarycontract'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayslip',
            unique_together={('salary_contract', 'month', 'year')},
        ),
    ]
