# Generated by Django 5.2.6 on 2025-09-29 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayslip',
            name='base_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
