# Generated by Django 5.2.6 on 2025-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_monthlypayslip_base_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('addition', 'Addition'), ('deduction', 'Deduction')], max_length=10),
        ),
    ]
