# Generated by Django 5.2.6 on 2025-09-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salaries', '0003_alter_salaryadjustment_adjustment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('payslib', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='salaries.monthlypayslip')),
            ],
        ),
    ]
