# Generated by Django 5.2.6 on 2025-09-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='payslib',
            new_name='payslip',
        ),
    ]
